# Generated by Django 6.0.2 on 2026-03-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
